name = "Rlearning"
uuid = "f9d14935-296e-4ed2-9f75-d9d303f09c5a"
authors = ["Graham Hindle"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
